/**
 * User-visible strings (pt-BR). Keys stay in English for code readability.
 */
export const strings = {
  appTitle: "Futball Manager",
  appSubtitle: "Configure as regras e sorteie os times na base, em qualquer dia.",
  tabbarNavLabel: "Navegação principal",
  sidebarNavLabel: "Navegação lateral",
  navHome: "Início",
  navReports: "Relatórios",
  navSquad: "Elenco",
  navMore: "Mais",
  navMatchLive: "Partida",
  squadPageTitle: "Elenco",
  squadPageSubtitle: "O time de domingo.",
  squadPageIntro:
    "Lista com todo mundo (ativos e inativos). Toca no card pra ajustar nível e perfil; o switch à direita liga ou desliga no elenco.",
  squadEmptyHint: "A lista está vazia: use o botão na barra acima para criar o primeiro jogador.",
  squadListError:
    "Não foi possível carregar o elenco. Verifique a conexão e tente novamente.",
  squadToolbarLabel: "Ações do elenco",
  squadSearchLabel: "Buscar por nome",
  squadSearchPlaceholder: "Digite o nome do jogador",
  squadSearchNoResults: "Nenhum jogador encontrado com esse nome.",
  squadAddPlayer: "Adicionar jogador",
  squadEdit: "Editar",
  squadRemove: "Remover",
  squadModalCreateTitle: "Novo jogador",
  squadModalEditTitle: "Editar jogador",
  squadFormSave: "Salvar",
  squadFormName: "Nome",
  squadFormActiveLabel: "Ativo no elenco",
  squadFormErrorName: "Indique o nome do jogador.",
  squadFormErrorStars: "O nível deve ser um número entre 0 e 5.",
  squadFormErrorGeneric: "Não foi possível salvar. Tente novamente.",
  squadPositionOptional: "Posição (opcional)",
  squadPositionPlaceholder: "ex.: GL, ZAG",
  squadPositionUnset: "Escolher posição…",
  squadPositionLegacyValue: "valor antigo",
  squadStarsHint:
    "Abra a lista para escolher o nível (0 a 5, passos de 0,5). As estrelas mostram o valor atual.",
  squadStarsOpt0: "0 — sem estrelas",
  squadStarsOpt5: "máximo",
  squadDeleteTitle: "Remover jogador",
  squadDeleteMessage:
    "Tem certeza de que deseja remover {name} do elenco? Essa ação não pode ser desfeita.",
  squadDeleteConfirm: "Remover",
  squadDeleteSubmitting: "Excluindo…",
  squadDeleteError: "Não foi possível excluir o jogador. Tente novamente.",
  squadStars: "Nível",
  squadProfile: "Perfil",
  squadProfileAttack: "Ataque",
  squadProfileDefense: "Defesa",
  squadProfileMixed: "Misto",
  squadPosition: "Posição",
  squadActive: "Ativo",
  squadInactive: "Inativo",
  squadRowStatusActiveAria: "Ativo no elenco",
  squadRowStatusInactiveAria: "Inativo no elenco",
  squadRowEditAria: "Editar jogador",
  squadRowRemoveAria: "Remover jogador do elenco",
  squadRowActiveSwitchAria: "Ativar ou desativar jogador no elenco e no sorteio",
  squadRowActiveToggleError: "Não foi possível atualizar. Toque para tentar novamente.",
  squadRowOpenSheetAria: "Abrir detalhes do jogador",
  squadPlayerSheetClose: "Fechar",
  squadPlayerSheetFallbackTitle: "Jogador",
  squadPlayerSheetSaveMeta: "Salvar alterações",
  squadPlayerSheetMetaSaving: "Salvando…",
  squadPlayerSheetMetaError: "Não foi possível salvar as alterações. Tente de novo.",
  toastRegionLabel: "Notificações",
  loadingSpinnerAria: "Carregando",
  toastMatchDayDrawOk: "Sorteio concluído — times e jogos já estão no servidor.",
  toastMatchDaySettingsOk: "Configurações do dia de jogo salvas.",
  toastMatchDayStartOk: "Cronômetro ligado: esta sub-partida passou a valer ao vivo.",
  toastMatchDayFinishOk: "Sub-partida terminada. Placar, fila e próximo jogo já foram atualizados.",
  toastMatchDayTimeExpiredOk: "Tempo da sub-partida acabou; o jogo foi fechado e o estado do dia foi atualizado.",
  toastMatchDayCloseOk: "Dia de jogo encerrado no sistema. Abra a aba Relatórios para ver o resumo, quando houver.",
  toastPlayerActivated: "Jogador ativado.",
  toastPlayerDeactivated: "Jogador inativado.",
  toastPlayerActiveFail: "Não foi possível atualizar o estado. Tente novamente.",
  toastPlayerCreated: "Jogador adicionado ao elenco.",
  toastPlayerMetaSaved: "Alterações salvas.",
  toastPlayerMetaFail: "Não foi possível salvar as alterações.",
  morePageTitle: "Mais",
  morePageSubtitle: "Configurações e extras.",
  morePagePlaceholder: "Opções adicionais em breve.",
  moreSessionTitle: "Sessão",
  moreLogoutHint: "Encerra a sessão e volta para o login.",
  moreLogoutButton: "Sair",
  apiStatusLabel: "Estado da API",
  apiStatusOk: "Conectado",
  apiStatusError: "Sem conexão com o servidor",
  apiStatusChecking: "Verificando…",
  playersOnBase: "Jogadores na base",
  homePlayersHint: "Resumo dos ativos; abra o elenco para criar, editar ou remover jogadores.",
  homeSquadTeaserLoading: "Carregando resumo…",
  homeSquadTeaserError: "Não foi possível carregar o resumo do elenco.",
  homeSquadActiveCount: "{n} jogador(es) ativo(s) na base.",
  homeSquadOpenRoster: "Abrir elenco completo →",
  homeSorteioCardTitleWithDate: "Sorteio na base — {date}",
  sundayGameSettingsTopic: "Configurações",
  sundayGameSettingsReadOnly: "Apenas organizadores podem alterar as configurações.",
  sundayGameDurationMin: "Duração de cada partida (minutos)",
  sundayGameMaxGoals: "Máximo de gols por time",
  sundayGameTeamCount: "Número de times",
  sundayGamePlayersPerTeam: "Jogadores por time",
  sundayGameFixedGk: "Goleiros Fixos",
  sundayGameFixedGkExplain:
    "Um goleiro fixo do elenco em cada gol (A = time 1, B = time 2). Dá pra fixar só um gol; no outro fica revezando. Só os dois primeiros times usam isso.",
  sundayGameGkRoleA: "Gol A — goleiro fixo",
  sundayGameGkRoleB: "Gol B — goleiro fixo",
  sundayGameGkUnset: "Sem goleiro fixo (revezar no gol)",
  sundayGameSettingsSave: "Salvar configurações",
  sundayGameSettingsSaving: "Salvando…",
  sundayGameUnsavedSettingsHint: "Salve as mudanças nas configurações antes de sortear.",
  sundayGameTeamsTopic: "Times",
  sundayGameTeamsDesc:
    "Em qualquer dia da semana pode sortear pelo elenco ativo (e sortear de novo se quiser). A escalação fecha quando começar a primeira partida.",
  sundayGameLineupProvisional:
    "Escalação provisória: sortear de novo só mexe no rascunho. Quando iniciar a partida, vale pro resto do dia.",
  sundayGameSaveBeforeDraw: "Salve as configurações acima antes de sortear.",
  sundayGameStartHold: "Segure para apitar o início do jogo",
  sundayGameStartHoldHint:
    "Segure o botão: a escalação fica oficial e a partida passa ao vivo (depois pode usar a tela Partida).",
  matchDayBannerTitle: "Dia de jogo",
  matchDayBannerSubtitle:
    "Janela de domingo na base (a partir das 06:00 no horário do servidor). O sorteio em si pode ser feito em qualquer dia.",
  matchDayCardTitle: "Hoje — domingo na base",
  matchDayCardIntro:
    "Sorteio automático a partir do elenco ativo, partida com cronômetro e marcação no servidor (vários celulares).",
  matchDayLoading: "Carregando dia de jogo…",
  matchDayLoadError: "Não foi possível carregar o dia de jogo.",
  matchDaySessionPickerLabel: "Ver dados de qual dia",
  matchDaySessionPickerToday: "Hoje (calendário do servidor)",
  matchDaySessionPickerEmpty: "Ainda não há sessões salvas nos últimos 14 dias.",
  matchDaySessionPickerHint:
    "Configurações e sorteio ficam no servidor; escolha outro dia para rever ou continuar de onde parou.",
  reportsPageHeaderTitle: "Relatórios",
  reportsPageHeaderSubtitle: "Apenas dias de jogo já encerrados.",
  reportsPageTitle: "Relatório do dia",
  reportsPageIntro: "Goleiros fixos, escalação e resumo ficam disponíveis só depois de encerrar o dia no sistema.",
  reportsClosedPickerLabel: "Dia encerrado",
  reportsSessionPickerHint: "Só aparecem aqui sessões com fase encerrada (rodada concluída).",
  reportsEmptyTitle: "Nenhum relatório ainda",
  reportsEmptyBody:
    "Quando houver pelo menos um dia de jogo encerrado nos últimos dias, o relatório completo aparece aqui. Por enquanto, use Início para o sorteio e Partida durante o jogo.",
  reportsEmptyCta: "Ir para o início",
  homeAlreadyPlayedTodayTitle: "Vocês já jogaram hoje.",
  homeAlreadyPlayedTodayClosedDetail:
    "Voltem outro dia para jogar de novo. Este dia está encerrado no sistema — no Início não dá mais para sortear nem mudar a escalação. Abra a aba Relatórios para ver o resumo.",
  homeAlreadyPlayedTodayMidDayHint:
    "Voltem outro dia para começar um sorteio novo na pelada. Se ainda houver jogos neste dia, continuem na aba Partida e encerre o dia no final.",
  matchDaySessionPhasePre: "Pré-partida",
  matchDaySessionPhaseLive: "Ao vivo",
  matchDaySessionPhaseClosed: "Encerrado",
  matchDayActionError: "Não foi possível concluir a ação. Tente novamente.",
  matchDayDismiss: "Fechar",
  matchDayDraw: "Sortear times",
  matchDayRedraw: "Sortear de novo",
  matchDayRedrawConfirm:
    "Substituir o sorteio e a sessão de hoje? As partidas e eventos atuais serão apagados.",
  matchDayDrawReadOnly: "Apenas organizadores podem sortear ou operar a partida.",
  matchDayNoSessionHint:
    'Ainda não tem sessão hoje: use "Sortear times" pra montar os times e o primeiro jogo.',
  matchDayFixturesTitle: "Jogos",
  matchDayFixturePending: "Pendente",
  matchDayFixtureLive: "Ao vivo",
  matchDayFixtureFinished: "Encerrado",
  matchDayLiveTitle: "Partida",
  matchDayNoFixture: "Sem partida para mostrar.",
  matchDayTimerLabel: "Tempo restante",
  matchDayStartMatch: "Iniciar partida",
  matchDayStartHold: "Segure para apitar o início do jogo",
  matchDayGoalHome: "Gol — time da casa",
  matchDayGoalAway: "Gol — visitante",
  matchDayGoalHomeAria: "Registrar gol do time da casa",
  matchDayGoalAwayAria: "Registrar gol do time visitante",
  matchDayGkHome: "Defesa do goleiro — casa",
  matchDayGkAway: "Defesa do goleiro — visitante",
  matchDayGkHomeAria: "Registrar defesa do goleiro do time da casa",
  matchDayGkAwayAria: "Registrar defesa do goleiro visitante",
  matchDayFinishHold: "Segure para encerrar a partida",
  matchDayTimeExpiredButton: "Encerrar (tempo acabou)",
  matchDayFixtureFinishedHint: "Esta partida foi encerrada.",
  sundayGameLiveCta: "Abrir tela da partida",
  sundayGameLiveCtaHint: "Placar, cronômetro, campo e eventos ficam na tela Partida.",
  sundayGamePendingKickoffHint:
    "Há uma partida pendente: use Segure para apitar o início no card do Início antes de ir ao painel ao vivo.",
  sundayGameCloseDayHold: "Segure para encerrar o dia",
  sundayGameCloseDayHint:
    "Encerra todas as partidas em aberto, registra o encerramento do dia e bloqueia novas alterações no sorteio e na escalação.",
  matchDayCloseReportTitle: "Relatório do dia",
  matchDayCloseReportFixtures: "Partidas",
  matchDayCloseReportPlayers: "Jogadores",
  matchDayCloseReportPlayersEmpty: "Nenhum evento com jogador identificado neste dia.",
  matchDayCloseReportNotContested: "Não disputada",
  matchDayCloseReportOrder: "Jogo {n}",
  matchDayCloseReportColPlayer: "Jogador",
  matchDayCloseReportColGoals: "Gols",
  matchDayCloseReportColAssists: "Assist.",
  matchDayCloseReportColSaves: "Defesas",
  matchDayCloseReportColYellow: "Amar.",
  matchDayCloseReportColRed: "Verm.",
  matchDayCloseReportColFixtures: "Jogos",
  matchDayArchiveFixedGkTitle: "Goleiros fixos",
  matchDayArchiveFixedGkLead: "Neste dia, os goleiros da meta foram:",
  matchDayArchiveFixedGkSlot: "Time {n}: {name}",
  matchDayArchiveFixedGkAria: "Goleiros fixos do dia encerrado",
  matchDayArchiveNoLineup: "Sem escalação registrada para este dia.",
  matchDayCloseReportEventsEmpty: "Sem eventos registrados nesta partida.",
  matchDayCloseReportEventNoClock: "—",
  matchLivePageTitle: "Partida ao vivo",
  matchLivePageSubtitle: "Campo e placar ao vivo. Toque nos jogadores para registrar gols e defesas.",
  matchLiveTimelineEmpty: "Nenhum evento registrado nesta partida ainda.",
  matchLiveTimelineGoal: "Gol",
  matchLiveTimelineGoalNamed: "Gol — {name}",
  matchLiveTimelineGoalScored: "{name} fez um GOL!",
  matchLiveTimelineGoalScoredAnonymous: "Gol!",
  matchLiveTimelineAssistUnderGoal: "Assistência: {name}",
  matchLiveTimelineSave: "Defesa",
  matchLiveTimelineSaveNamed: "Defesa — {name}",
  matchLiveTimelineUnknown: "Evento",
  matchLiveTimelineAssist: "Assistência",
  matchLiveTimelineAssistNamed: "Assistência — {name}",
  matchLiveTimelineYellow: "Cartão amarelo",
  matchLiveTimelineYellowNamed: "Cartão amarelo — {name}",
  matchLiveTimelineRed: "Cartão vermelho",
  matchLiveTimelineRedNamed: "Cartão vermelho — {name}",
  matchLiveNoActive: "Não há partida ao vivo agora. Volte ao início para sortear ou aguardar o início.",
  matchLiveBackHome: "Voltar ao início",
  matchLiveKingNext: "Próximos na fila: {slots}.",
  matchLiveGoalLimitTitleWin: "{team} ganhou!",
  matchLiveGoalLimitTitleDraw: "Sub-partida encerrada em empate.",
  matchLiveGoalLimitScoreAria: "Placar {homeG}:{awayG}",
  matchLiveGoalLimitGoalsHeading: "Gols",
  matchLiveGoalLimitGoalLine: "{name} ({team})",
  matchLiveGoalLimitGoalLineAnon: "Gol ({team})",
  matchLiveGoalLimitRotation: "O {incoming} entra no lugar do {loser}, que saiu de campo.",
  matchLiveGoalLimitGoalsEmpty: "Nenhum gol com jogador identificado na sub-partida.",
  matchLiveGoalLimitOk: "Continuar",
  matchLiveClockOvertimeWarning:
    "O tempo de jogo útil atingiu ou passou do limite com acréscimo ({limit}). Considere encerrar a partida ou registrar o fim do tempo.",
  matchLiveClockPause: "Pausar",
  matchLiveClockResume: "Retomar",
  matchLiveClockPauseAria: "Pausar o cronômetro da partida",
  matchLiveClockResumeAria: "Retomar o cronômetro da partida",
  matchLiveClockStoppage: "Acréscimo: {time}",
  matchLiveFinishMatch: "Finalizar partida",
  matchLiveFinishMatchAria: "Finalizar a partida ao vivo",
  matchLiveFinishConfirm:
    "Encerrar esta partida agora? Os eventos já registrados (gols, defesas, cartões, assistências) permanecem salvos. A próxima partida será preparada automaticamente quando houver fila de times.",
  matchLiveFinishDenied: "Sem permissão para finalizar a partida.",
  matchLiveMatchActionsGroup: "Pausar ou retomar o cronômetro da partida",
  matchLiveAwaitingKickoff:
    "Esta partida ainda não começou. Inicie quando estiver pronto — o cronômetro e o placar só rodam após o início.",
  matchLiveStartMatchCta: "Iniciar partida",
  matchLiveStartMatchNoPermission: "Apenas organizadores podem dar início à partida.",
  matchLiveCloseDayHold: "Segure para dar fim às partidas do dia.",
  matchDayRuleDuration: "Duração (minutos)",
  matchDayRuleMaxGoals: "Máx. de gols por time",
  matchDayRuleSave: "Aplicar regras aos jogos pendentes",
  matchDayPitchTitle: "Escalação",
  matchDayPitchAria: "Escalação dos dois times",
  matchDayTeam1: "Time 1",
  matchDayTeam2: "Time 2",
  matchDayTeamN: "Time {n}",
  matchDayNoPlayersInTeam: "(sem jogadores)",
  playersEmpty: "Ainda não há jogadores cadastrados.",
  loginTitle: "Entrar",
  loginSubtitle: "Acesse sua conta para continuar.",
  loginUsernameLabel: "Nome de usuário",
  loginUsernamePlaceholder: "exemplo: maria.silva",
  loginPasswordLabel: "Senha",
  loginPasswordPlaceholder: "••••••••",
  loginSubmit: "Entrar",
  loginSubmitting: "Entrando…",
  loginErrorInvalid: "Usuário ou senha incorretos.",
  loginErrorNetwork: "Não foi possível conectar ao servidor. Tente novamente.",
  authChecking: "Verificando sessão…",
  moreLogoutWorking: "Saindo…",
  usersAdminTitle: "Usuários",
  usersAdminIntro:
    "Crie e gerencie contas de organizadores (e administradores). O primeiro acesso é entregue com segurança (senha definida aqui).",
  usersAdminNewAccessButton: "Novo acesso",
  usersAdminModalCreateTitle: "Criar acesso de organizador",
  usersAdminModalCreateHint:
    "Defina nome de usuário, telefone e senha inicial. O organizador poderá alterar a senha depois do primeiro login, quando existir essa opção.",
  usersAdminModalEditTitle: "Detalhes do usuário",
  usersAdminModalDismissBackdrop: "Fechar janela",
  usersAdminModalClose: "Fechar",
  usersAdminFieldId: "Identificador (UUID)",
  usersAdminCreateSubmit: "Criar acesso",
  usersAdminListTitle: "Lista de usuários",
  usersAdminListError: "Não foi possível carregar a lista.",
  usersAdminListEmpty: "Ainda não há outros usuários.",
  usersAdminColUser: "Usuário",
  usersAdminColRole: "Função",
  usersAdminColActions: "Ações",
  usersAdminPhoneLabel: "Telefone",
  usersAdminEdit: "Editar",
  usersAdminDelete: "Excluir",
  usersAdminSave: "Salvar",
  usersAdminCancel: "Cancelar",
  usersAdminSaving: "Salvando…",
  usersAdminNewPasswordOptional: "Nova senha (opcional)",
  usersAdminDeleteConfirm:
    "Excluir este usuário? Essa ação não pode ser desfeita.",
  usersAdminErrorGeneric:
    "Operação falhou. Verifique os dados e tente novamente.",
  usersAdminErrorDuplicate: "Já existe um usuário com esse nome.",
  usersAdminErrorNoChanges: "Indique pelo menos um campo a alterar.",
  usersAdminRoleOrganizer: "Organizador",
  usersAdminRoleAdmin: "Administrador",
  usersAdminRoleSuperAdmin: "Super administrador",

  squadPositionOptGL: "GL — Goleiro",
  squadPositionOptLAT: "LAT — Lateral",
  squadPositionOptZAG: "ZAG — Zagueiro",
  squadPositionOptAL: "AL — Ala",
  squadPositionOptATA: "ATA — Atacante",

  jogoRolandoSandboxTitle: "Jogo ao vivo (sandbox)",
  jogoRolandoSandboxSubtitle: "Rota só para desenvolvimento e testes de UI.",
  jogoRolandoSandboxHeading: "Área de testes",
  jogoRolandoSandboxBlurb:
    "Esta página não exige login. Use o espaço abaixo para experimentar a tela de jogo ao vivo sem afetar a navegação principal.",
  jogoRolandoSandboxLinkLogin: "Ir para o login",
  jogoRolandoSandboxLinkApp: "Ir para a app",
  jogoRolandoPitchAria: "Campo de futebol visto de cima",
  jogoRolandoPlayersPerSide: "Jogadores por time",
  jogoRolandoPlayersPerSideHint: "Até 8 de cada lado (inclui goleiro).",
  jogoRolandoPlayersPerSideOption: "{n} jogadores",
  jogoRolandoFormationLine: "Formação ilustrada: {name}.",
  jogoRolandoFormation1: "só goleiro",
  jogoRolandoFormation2: "goleiro e último homem ao centro",
  jogoRolandoFormation3: "linha de dois na frente do goleiro (zaga society)",
  jogoRolandoFormation4: "triângulo 1-2 (volante e duas alas)",
  jogoRolandoFormation5: "losango 1-2-1 (volante, alas e referência)",
  jogoRolandoFormation6: "2-2-1 (zaga dupla, dois meio-campistas, referência)",
  jogoRolandoFormation7: "3-2-1 (linha de três, dois meias, ponta)",
  jogoRolandoFormation8: "3-3-1 (três defesas, três meios, atacante central)",
  jogoRolandoSlotEmptyHint:
    "Slots sem nome mostram o ícone de perfil; com nome, aparecem as iniciais.",
  jogoRolandoSandboxMockLineups:
    "Nesta página os slots usam nomes fictícios; na app real vêm do elenco.",
  jogoRolandoUnknownPlayer: "Jogador",
  jogoRolandoPlayerSlotActions: "Ações de {name}",
  jogoRolandoActionCardAria: "Ações do jogador",
  jogoRolandoLivePlayerModalTitle: "{name}",
  jogoRolandoLivePlayerModalIntro:
    "Um evento por confirmação: no máximo 1 gol, 1 cartão amarelo, 1 vermelho ou 1 defesa. Com gol, pode indicar assistência.",
  jogoRolandoLivePlayerModalSaveToast: "Evento registrado na partida ao vivo e sincronizado com o dia de jogo.",
  jogoRolandoLivePlayerModalGoalIconAlt: "Ícone de gol",
  jogoRolandoLivePlayerModalAssistIconAlt: "Ícone de assistência",
  jogoRolandoLivePlayerModalGoalkeeperIconAlt: "Ícone de goleiro",
  jogoRolandoLivePlayerModalYellowCardIconAlt: "Ícone de cartão amarelo",
  jogoRolandoLivePlayerModalRedCardIconAlt: "Ícone de cartão vermelho",
  jogoRolandoLivePlayerModalGols: "Gols",
  jogoRolandoLivePlayerModalAssists: "Assistências",
  jogoRolandoLivePlayerModalYellowCards: "Cartões amarelos",
  jogoRolandoLivePlayerModalRedCards: "Cartões vermelhos",
  jogoRolandoLivePlayerModalDefesas: "Defesas",
  jogoRolandoLivePlayerModalCountDown: "Diminuir {label}",
  jogoRolandoLivePlayerModalCountUp: "Aumentar {label}",
  jogoRolandoMatchPanelAria: "Painel da partida",
  jogoRolandoMatchHomeName: "Casa",
  jogoRolandoMatchVisitorName: "Visitante",
  jogoRolandoMatchPlay: "Iniciar",
  jogoRolandoMatchPause: "Pausar",
  jogoRolandoMatchClockLabel: "Tempo de jogo",
  jogoRolandoMatchTimelineAriaNone: "Linha do tempo do jogo. Sem eventos.",
  jogoRolandoMatchTimelineAriaOne: "Linha do tempo do jogo. 1 evento.",
  jogoRolandoMatchTimelineAriaSome: "Linha do tempo do jogo. {n} eventos.",
  jogoRolandoMatchTimelineEmpty: "Ainda não há eventos. Toque em um jogador e use Salvar.",
  jogoRolandoLivePlayerModalGoalAssistLabel: "Assistência do gol",
  jogoRolandoLivePlayerModalGoalAssistNoneOption: "Sem assistência",
  jogoRolandoMatchGoalAssistLine: "Assistência: {name}.",
  jogoRolandoMatchGoalAssistNone: "Sem assistência.",
  jogoRolandoMatchMsgGoalOne: "{name} marcou um GOL!",
  jogoRolandoMatchMsgGoalsN: "{name} marcou {n} gols!",
  jogoRolandoMatchMsgAssistOne: "{name} deu uma assistência!",
  jogoRolandoMatchMsgAssistsN: "{name} deu {n} assistências!",
  jogoRolandoMatchMsgYellowOne: "{name} levou um cartão amarelo!",
  jogoRolandoMatchMsgYellowN: "{name} levou {n} cartões amarelos!",
  jogoRolandoMatchMsgRedOne: "{name} levou um cartão vermelho!",
  jogoRolandoMatchMsgRedN: "{name} levou {n} cartões vermelhos!",
  jogoRolandoMatchMsgSaveOne: "{name} fez uma defesa!",
  jogoRolandoMatchMsgSavesN: "{name} fez {n} defesas!",
  jogoRolandoMatchEventHeadline: "{player} · {team}",
  jogoRolandoMatchStatSep: " · ",
  jogoRolandoMatchStatGoals1: "1 gol",
  jogoRolandoMatchStatGoalsN: "{n} gols",
  jogoRolandoMatchStatAssists1: "1 assistência",
  jogoRolandoMatchStatAssistsN: "{n} assistências",
  jogoRolandoMatchStatYellow1: "1 cartão amarelo",
  jogoRolandoMatchStatYellowN: "{n} cartões amarelos",
  jogoRolandoMatchStatRed1: "1 cartão vermelho",
  jogoRolandoMatchStatRedN: "{n} cartões vermelhos",
  jogoRolandoMatchStatSaves1: "1 defesa",
  jogoRolandoMatchStatSavesN: "{n} defesas",
  jogoRolandoActionCardClose: "Fechar",
  jogoRolandoActionCardGol: "Gol",
  jogoRolandoActionCardAssist: "Assistência",
  jogoRolandoActionCardDefesa: "Defesa",
};

/** Society: códigos gravados na API (até 64 caracteres); rótulos em pt-BR (Brasil). */
export const squadPositionSelectOptions = [
  { value: "", label: strings.squadPositionUnset },
  { value: "GL", label: strings.squadPositionOptGL },
  { value: "LAT", label: strings.squadPositionOptLAT },
  { value: "ZAG", label: strings.squadPositionOptZAG },
  { value: "AL", label: strings.squadPositionOptAL },
  { value: "ATA", label: strings.squadPositionOptATA },
];
