/**
 * User-visible strings (pt-BR). Keys stay in English for code readability.
 */
export const strings = {
  appTitle: "Futball Manager",
  appSubtitle: "Organize o seu grupo de domingo.",
  tabbarNavLabel: "Navegação principal",
  sidebarNavLabel: "Navegação lateral",
  navHome: "Início",
  navSquad: "Elenco",
  navMore: "Mais",
  squadPageTitle: "Elenco",
  squadPageSubtitle: "A equipe de domingo.",
  squadPageIntro:
    "Base de jogadores do grupo: ver, adicionar, editar ou remover registos (sincronizado com o servidor).",
  squadListError: "Não foi possível carregar o elenco. Verifique a ligação e tente novamente.",
  squadToolbarLabel: "Filtros e ações do elenco",
  squadShowInactive: "Mostrar inativos",
  squadAddPlayer: "Adicionar jogador",
  squadEdit: "Editar",
  squadRemove: "Remover",
  squadModalCreateTitle: "Novo jogador",
  squadModalEditTitle: "Editar jogador",
  squadFormSave: "Guardar",
  squadFormName: "Nome",
  squadFormActiveLabel: "Ativo no elenco",
  squadFormErrorName: "Indique o nome do jogador.",
  squadFormErrorStars: "O nível deve ser um número entre 0 e 5.",
  squadFormErrorGeneric: "Não foi possível guardar. Tente novamente.",
  squadPositionOptional: "Posição (opcional)",
  squadPositionPlaceholder: "ex.: GR, ZAG",
  squadDeleteTitle: "Remover jogador",
  squadDeleteMessage:
    "Tem a certeza de que quer remover {name} do elenco? Esta ação não pode ser anulada.",
  squadDeleteConfirm: "Remover",
  squadStars: "Nível",
  squadProfile: "Perfil",
  squadProfileAttack: "Ataque",
  squadProfileDefense: "Defesa",
  squadProfileMixed: "Misto",
  squadPosition: "Posição",
  squadActive: "Ativo",
  squadInactive: "Inativo",
  morePageTitle: "Mais",
  morePageSubtitle: "Definições e extras.",
  morePagePlaceholder: "Opções adicionais em breve.",
  moreSessionTitle: "Sessão",
  moreLogoutHint: "Encerra a sessão e volta para a tela de login.",
  moreLogoutButton: "Sair",
  apiStatusLabel: "Estado da API",
  apiStatusOk: "Conectado",
  apiStatusError: "Sem ligação ao servidor",
  apiStatusChecking: "Verificando…",
  playersOnBase: "Jogadores na base",
  playersEmpty: "Ainda não há jogadores cadastrados.",
  loginTitle: "Entrar",
  loginSubtitle: "Acesse sua conta para continuar.",
  loginUsernameLabel: "Nome de usuário",
  loginUsernamePlaceholder: "exemplo: maria.silva",
  loginPasswordLabel: "Senha",
  loginPasswordPlaceholder: "••••••••",
  loginSubmit: "Entrar",
  loginSubmitting: "A entrar…",
  loginErrorInvalid: "Utilizador ou palavra-passe incorretos.",
  loginErrorNetwork: "Não foi possível contactar o servidor. Tente novamente.",
  authChecking: "A verificar sessão…",
  moreLogoutWorking: "A sair…",
  usersAdminTitle: "Utilizadores",
  usersAdminIntro:
    "Crie e gira contas de organizadores (e administradores). O primeiro acesso é-lhes entregue em segurança (palavra-passe definida aqui).",
  usersAdminNewAccessButton: "Novo acesso",
  usersAdminModalCreateTitle: "Criar acesso de organizador",
  usersAdminModalCreateHint:
    "Defina nome de utilizador, telefone e palavra-passe inicial. O organizador poderá alterar a palavra-passe depois do primeiro login, quando existir essa opção.",
  usersAdminModalEditTitle: "Detalhes do utilizador",
  usersAdminModalDismissBackdrop: "Fechar diálogo",
  usersAdminModalClose: "Fechar",
  usersAdminFieldId: "Identificador (UUID)",
  usersAdminCreateSubmit: "Criar acesso",
  usersAdminListTitle: "Lista de utilizadores",
  usersAdminListError: "Não foi possível carregar a lista.",
  usersAdminListEmpty: "Ainda não há outros utilizadores.",
  usersAdminColUser: "Utilizador",
  usersAdminColRole: "Função",
  usersAdminColActions: "Ações",
  usersAdminPhoneLabel: "Telefone",
  usersAdminEdit: "Editar",
  usersAdminDelete: "Eliminar",
  usersAdminSave: "Guardar",
  usersAdminCancel: "Cancelar",
  usersAdminSaving: "A guardar…",
  usersAdminNewPasswordOptional: "Nova palavra-passe (opcional)",
  usersAdminDeleteConfirm: "Eliminar este utilizador? Esta ação não pode ser anulada.",
  usersAdminErrorGeneric: "Operação falhou. Verifique os dados e tente novamente.",
  usersAdminErrorDuplicate: "Já existe um utilizador com esse nome.",
  usersAdminErrorNoChanges: "Indique pelo menos um campo a alterar.",
  usersAdminRoleOrganizer: "Organizador",
  usersAdminRoleAdmin: "Administrador",
  usersAdminRoleSuperAdmin: "Super administrador",
};
