/**
 * User-visible strings (pt-BR). Keys stay in English for code readability.
 */
export const strings = {
  appTitle: "Futball Manager",
  appSubtitle: "Organize seu grupo de domingo.",
  tabbarNavLabel: "Navegação principal",
  sidebarNavLabel: "Navegação lateral",
  navHome: "Início",
  navSquad: "Elenco",
  navMore: "Mais",
  squadPageTitle: "Elenco",
  squadPageSubtitle: "O time de domingo.",
  squadPageIntro:
    "Lista com todo mundo (ativos e inativos). Toca no card pra ajustar nível e perfil; o switch à direita liga ou desliga no elenco.",
  squadEmptyHint: "A lista está vazia: use o botão na barra acima para criar o primeiro jogador.",
  squadListError:
    "Não foi possível carregar o elenco. Verifique a conexão e tente novamente.",
  squadToolbarLabel: "Ações do elenco",
  squadSearchLabel: "Buscar por nome",
  squadSearchPlaceholder: "Digite o nome do jogador",
  squadSearchNoResults: "Nenhum jogador encontrado com esse nome.",
  squadAddPlayer: "Adicionar jogador",
  squadEdit: "Editar",
  squadRemove: "Remover",
  squadModalCreateTitle: "Novo jogador",
  squadModalEditTitle: "Editar jogador",
  squadFormSave: "Salvar",
  squadFormName: "Nome",
  squadFormActiveLabel: "Ativo no elenco",
  squadFormErrorName: "Indique o nome do jogador.",
  squadFormErrorStars: "O nível deve ser um número entre 0 e 5.",
  squadFormErrorGeneric: "Não foi possível salvar. Tente novamente.",
  squadPositionOptional: "Posição (opcional)",
  squadPositionPlaceholder: "ex.: GL, ZAG",
  squadPositionUnset: "Escolher posição…",
  squadPositionLegacyValue: "valor antigo",
  squadStarsHint:
    "Abra a lista para escolher o nível (0 a 5, passos de 0,5). As estrelas mostram o valor atual.",
  squadStarsOpt0: "0 — sem estrelas",
  squadStarsOpt5: "máximo",
  squadDeleteTitle: "Remover jogador",
  squadDeleteMessage:
    "Tem certeza de que deseja remover {name} do elenco? Essa ação não pode ser desfeita.",
  squadDeleteConfirm: "Remover",
  squadDeleteSubmitting: "Excluindo…",
  squadDeleteError: "Não foi possível excluir o jogador. Tente novamente.",
  squadStars: "Nível",
  squadProfile: "Perfil",
  squadProfileAttack: "Ataque",
  squadProfileDefense: "Defesa",
  squadProfileMixed: "Misto",
  squadPosition: "Posição",
  squadActive: "Ativo",
  squadInactive: "Inativo",
  squadRowStatusActiveAria: "Ativo no elenco",
  squadRowStatusInactiveAria: "Inativo no elenco",
  squadRowEditAria: "Editar jogador",
  squadRowRemoveAria: "Remover jogador do elenco",
  squadRowActiveSwitchAria: "Ativar ou desativar jogador no elenco e no sorteio",
  squadRowActiveToggleError: "Não foi possível atualizar. Toque para tentar de novo.",
  squadRowOpenSheetAria: "Abrir detalhes do jogador",
  squadPlayerSheetClose: "Fechar",
  squadPlayerSheetFallbackTitle: "Jogador",
  squadPlayerSheetSaveMeta: "Salvar alterações",
  squadPlayerSheetMetaSaving: "Salvando…",
  squadPlayerSheetMetaError: "Não deu pra salvar as alterações. Tenta de novo.",
  toastRegionLabel: "Notificações",
  toastPlayerActivated: "Jogador ativado.",
  toastPlayerDeactivated: "Jogador inativado.",
  toastPlayerActiveFail: "Não foi possível atualizar o estado. Tente novamente.",
  toastPlayerCreated: "Jogador adicionado ao elenco.",
  toastPlayerMetaSaved: "Alterações salvas.",
  toastPlayerMetaFail: "Não deu pra salvar as alterações.",
  morePageTitle: "Mais",
  morePageSubtitle: "Configurações e extras.",
  morePagePlaceholder: "Opções adicionais em breve.",
  moreSessionTitle: "Sessão",
  moreLogoutHint: "Fecha a sessão e volta pro login.",
  moreLogoutButton: "Sair",
  apiStatusLabel: "Estado da API",
  apiStatusOk: "Conectado",
  apiStatusError: "Sem conexão com o servidor",
  apiStatusChecking: "Verificando…",
  playersOnBase: "Jogadores na base",
  homePlayersHint: "Resumo dos ativos; abra o elenco para criar, editar ou remover jogadores.",
  homeSquadTeaserLoading: "Carregando resumo…",
  homeSquadTeaserError: "Não foi possível carregar o resumo do elenco.",
  homeSquadActiveCount: "{n} jogador(es) ativo(s) na base.",
  homeSquadOpenRoster: "Abrir elenco completo →",
  sundayGameTitle: "Jogo de domingo",
  sundayGameSettingsTopic: "Configurações",
  sundayGameSettingsReadOnly: "Apenas organizadores podem alterar as configurações.",
  sundayGameDurationMin: "Duração de cada partida (minutos)",
  sundayGameMaxGoals: "Máximo de gols por time",
  sundayGameTeamCount: "Número de times",
  sundayGamePlayersPerTeam: "Jogadores por time",
  sundayGameFixedGk: "Goleiros Fixos",
  sundayGameFixedGkExplain:
    "Um goleiro fixo do elenco em cada gol (A = time 1, B = time 2). Dá pra fixar só um gol; no outro fica revezando. Só os dois primeiros times usam isso.",
  sundayGameGkRoleA: "Gol A — goleiro fixo",
  sundayGameGkRoleB: "Gol B — goleiro fixo",
  sundayGameGkUnset: "Sem goleiro fixo (revezar no gol)",
  sundayGameSettingsSave: "Salvar configurações",
  sundayGameSettingsSaving: "Salvando…",
  sundayGameUnsavedSettingsHint: "Salve as mudanças nas configurações antes de sortear.",
  sundayGameTeamsTopic: "Times",
  sundayGameTeamsDesc:
    "Dá pra sortear os times pelo elenco ativo (e sortear de novo se quiser). A escalação fecha quando começar a primeira partida.",
  sundayGameLineupProvisional:
    "Escalação provisória: sortear de novo só mexe no rascunho. Ao apitar o início, vale pro resto do dia.",
  sundayGameSaveBeforeDraw: "Salve as configurações acima antes de sortear.",
  sundayGameStartHold: "Segure para apitar o início",
  sundayGameStartHoldHint:
    "Segure o botão para apitar o início: aí a escalação atual fica oficial e a partida começa (painel ao vivo).",
  matchDayBannerTitle: "Dia de jogo",
  matchDayBannerSubtitle:
    "Domingo a partir das 06:00 (horário do servidor): manda ver nos times e nas partidas.",
  matchDayCardTitle: "Hoje — domingo na base",
  matchDayCardIntro:
    "Sorteio automático a partir do elenco ativo, partida com cronômetro e marcação no servidor (vários celulares).",
  matchDayLoading: "Carregando dia de jogo…",
  matchDayLoadError: "Não foi possível carregar o dia de jogo.",
  matchDayActionError: "Não foi possível concluir a ação. Tente novamente.",
  matchDayDismiss: "Fechar",
  matchDayDraw: "Sortear times",
  matchDayRedraw: "Sortear de novo",
  matchDayRedrawConfirm:
    "Substituir o sorteio e a sessão de hoje? As partidas e eventos atuais serão apagados.",
  matchDayDrawReadOnly: "Apenas organizadores podem sortear ou operar a partida.",
  matchDayNoSessionHint:
    'Ainda não tem sessão hoje: use "Sortear times" pra montar os times e o primeiro jogo.',
  matchDayFixturesTitle: "Jogos",
  matchDayFixturePending: "Pendente",
  matchDayFixtureLive: "Ao vivo",
  matchDayFixtureFinished: "Encerrado",
  matchDayLiveTitle: "Partida",
  matchDayNoFixture: "Sem partida para mostrar.",
  matchDayCurrentMatch: "Partida em foco",
  matchDayTimerLabel: "Tempo restante",
  matchDayStartMatch: "Apitar início",
  matchDayStartHold: "Segure para apitar o início",
  matchDayGoalHome: "Gol — time da casa",
  matchDayGoalAway: "Gol — visitante",
  matchDayGoalHomeAria: "Registrar gol do time da casa",
  matchDayGoalAwayAria: "Registrar gol do time visitante",
  matchDayGkHome: "Defesa do goleiro — casa",
  matchDayGkAway: "Defesa do goleiro — visitante",
  matchDayGkHomeAria: "Registrar defesa do goleiro do time da casa",
  matchDayGkAwayAria: "Registrar defesa do goleiro visitante",
  matchDayFinishHold: "Segure para encerrar a partida",
  matchDayFixtureFinishedHint: "Esta partida foi encerrada.",
  matchDayRuleDuration: "Duração (minutos)",
  matchDayRuleMaxGoals: "Máx. de gols por time",
  matchDayRuleSave: "Aplicar regras aos jogos pendentes",
  matchDayPitchTitle: "Escalação",
  matchDayPitchAria: "Escalação dos dois times",
  matchDayTeam1: "Time 1",
  matchDayTeam2: "Time 2",
  matchDayTeamN: "Time {n}",
  matchDayNoPlayersInTeam: "(sem jogadores)",
  playersEmpty: "Ainda não há jogadores cadastrados.",
  loginTitle: "Entrar",
  loginSubtitle: "Acesse sua conta para continuar.",
  loginUsernameLabel: "Nome de usuário",
  loginUsernamePlaceholder: "exemplo: maria.silva",
  loginPasswordLabel: "Senha",
  loginPasswordPlaceholder: "••••••••",
  loginSubmit: "Entrar",
  loginSubmitting: "Entrando…",
  loginErrorInvalid: "Usuário ou senha incorretos.",
  loginErrorNetwork: "Não foi possível conectar ao servidor. Tente novamente.",
  authChecking: "Verificando sessão…",
  moreLogoutWorking: "Saindo…",
  usersAdminTitle: "Usuários",
  usersAdminIntro:
    "Crie e gerencie contas de organizadores (e administradores). O primeiro acesso é entregue com segurança (senha definida aqui).",
  usersAdminNewAccessButton: "Novo acesso",
  usersAdminModalCreateTitle: "Criar acesso de organizador",
  usersAdminModalCreateHint:
    "Defina nome de usuário, telefone e senha inicial. O organizador poderá alterar a senha depois do primeiro login, quando existir essa opção.",
  usersAdminModalEditTitle: "Detalhes do usuário",
  usersAdminModalDismissBackdrop: "Fechar janela",
  usersAdminModalClose: "Fechar",
  usersAdminFieldId: "Identificador (UUID)",
  usersAdminCreateSubmit: "Criar acesso",
  usersAdminListTitle: "Lista de usuários",
  usersAdminListError: "Não foi possível carregar a lista.",
  usersAdminListEmpty: "Ainda não há outros usuários.",
  usersAdminColUser: "Usuário",
  usersAdminColRole: "Função",
  usersAdminColActions: "Ações",
  usersAdminPhoneLabel: "Telefone",
  usersAdminEdit: "Editar",
  usersAdminDelete: "Excluir",
  usersAdminSave: "Salvar",
  usersAdminCancel: "Cancelar",
  usersAdminSaving: "Salvando…",
  usersAdminNewPasswordOptional: "Nova senha (opcional)",
  usersAdminDeleteConfirm:
    "Excluir este usuário? Essa ação não pode ser desfeita.",
  usersAdminErrorGeneric:
    "Operação falhou. Verifique os dados e tente novamente.",
  usersAdminErrorDuplicate: "Já existe um usuário com esse nome.",
  usersAdminErrorNoChanges: "Indique pelo menos um campo a alterar.",
  usersAdminRoleOrganizer: "Organizador",
  usersAdminRoleAdmin: "Administrador",
  usersAdminRoleSuperAdmin: "Super administrador",

  squadPositionOptGL: "GL — Goleiro",
  squadPositionOptLAT: "LAT — Lateral",
  squadPositionOptZAG: "ZAG — Zagueiro",
  squadPositionOptAL: "AL — Ala",
  squadPositionOptATA: "ATA — Atacante",
};

/** Society: códigos gravados na API (até 64 caracteres); rótulos em pt-BR (Brasil). */
export const squadPositionSelectOptions = [
  { value: "", label: strings.squadPositionUnset },
  { value: "GL", label: strings.squadPositionOptGL },
  { value: "LAT", label: strings.squadPositionOptLAT },
  { value: "ZAG", label: strings.squadPositionOptZAG },
  { value: "AL", label: strings.squadPositionOptAL },
  { value: "ATA", label: strings.squadPositionOptATA },
];
